name: lighthouse
on:
  pull_request:
  push: # to be removed when opening PR
    branches: # to be removed when opening PR
      - lighthouse-ci # to be removed when opening PR

jobs:
  lighthouseci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: yarn install && yarn global add -g @lhci/cli@0.8.x
      - run: yarn build
        env:
          NEXT_PUBLIC_DEMO_MOVIES_HOST: ${{ secrets.NEXT_PUBLIC_DEMO_MOVIES_HOST }}
          NEXT_PUBLIC_DEMO_MOVIES_API_KEY: ${{ secrets.NEXT_PUBLIC_DEMO_MOVIES_API_KEY }}
      - run: lhci autorun --collect.staticDistDir=./.next
